name: "Build & Release"

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller
      - name: Build executable
        run: |
          pyinstaller --onefile main.py utilities.py promogames.py
      - name: Rename executable
        run: |
          Rename-Item -Path dist/main.exe -NewName MasterHamsterKombatBot-v2.3.${{ github.run_number }}-windows.exe
        shell: pwsh
      - name: Zip the exe
        run: |
          Compress-Archive -Path "dist/MasterHamsterKombatBot-v2.3.${{ github.run_number }}-windows.exe" -DestinationPath "dist/MasterHamsterKombatBot-v2.3.${{ github.run_number }}-windows.zip"
        shell: pwsh
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: dist/MasterHamsterKombatBot-v2.3.${{ github.run_number }}-windows.zip

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller
      - name: Build executable
        run: |
          pyinstaller --windowed --onefile main.py utilities.py promogames.py
      - name: Rename app
        run: |
          mv dist/main.app "MasterHamsterKombatBot-v2.3.${{ github.run_number }}-macARM.app"
      - name: Zip the app
        run: |
          zip -r "MasterHamsterKombatBot-v2.3.${{ github.run_number }}-macARM.zip" "MasterHamsterKombatBot-v2.3.${{ github.run_number }}-macARM.app"
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-build
          path: "MasterHamsterKombatBot-v2.3.${{ github.run_number }}-macARM.zip"

  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller
      - name: Build executable
        run: |
          pyinstaller --windowed --onefile main.py utilities.py promogames.py
      - name: Rename executable
        run: |
          mv dist/main.deb "MasterHamsterKombatBot-v2.3.${{ github.run_number }}-ubuntu.deb"
      - name: Zip the executable
        run: |
          zip -r "MasterHamsterKombatBot-v2.3.${{ github.run_number }}-ubuntu.zip" "MasterHamsterKombatBot-v2.3.${{ github.run_number }}-ubuntu.deb"
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ubuntu-build
          path: "MasterHamsterKombatBot-v2.3.${{ github.run_number }}-ubuntu.zip"
          
          
  create-release:
    needs: [build-windows, build-macos, build-ubuntu]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download Windows build
        uses: actions/download-artifact@v4
        with:
          name: windows-build
          path: ./build
      - name: Download macOS build
        uses: actions/download-artifact@v4
        with:
          name: macos-build
          path: ./build
      - name: Download Ubuntu build
        uses: actions/download-artifact@v4
        with:
          name: ubuntu-build
          path: ./build
      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: ./build/*
          tag: v2.3.${{ github.run_number }}
          token: ${{ secrets.GITHUB_TOKEN }}
